### PR TITLE
Add the C# build manual

### PR DESCRIPTION
**Pull request by cadichris**
To catch up with the Java and C++ bits.

### CODE REVIEW

**Review by aatwi — APPROVED** [review]

**Review by mengdaming — APPROVED** [review]

**Comment by philou** [comment]
We should also add a link to the [introduction markdown file ](https://github.com/murex/mikado-testbuilders-kata/blob/master/docs/1_Introduction.md)

**Review by philou — CHANGES_REQUESTED** [review]
We should also add a link to the [introduction markdown file ](https://github.com/murex/mikado-testbuilders-kata/blob/master/docs/1_Introduction.md)

**Comment by cadichris** [comment]
Thanks @philou. 

I added the references.
The links in the homework are absolute http links (as opposed to relative links), I don't know if that's on purpose but I followed the convention :D

**Review by aatwi — APPROVED** [review]

**Comment by aatwi** [comment]
> Thanks @philou.
> 
> I added the references.
> The links in the homework are absolute http links (as opposed to relative links), I don't know if that's on purpose but I followed the convention :D

They are absolute because that's the only way they work from an email template (in case we send the Homework as an email)  :D

**Pull request merged**
